# Functions for working with .asc eye-tracking files generated by the Eyetrack program (https://blogs.umass.edu/eyelab/software/)

# Martin R. Vasilev, 2017

get_id<- function(string){substr(string, unlist(gregexpr(pattern =' ',trial_text[1]))[2]+1, nchar(string))}

get_exp_trials<- function(trials){letter<- substr(trials, 1, 1); trials[which(letter!="P" &  letter!="F")]}

get_SFIX_stamp<- function(string){as.numeric(substr(string, unlist(gregexpr(pattern ='   ',string))+3, nchar(string)))}

get_EFIX_stamp<- function(string){as.numeric(substr(string, unlist(gregexpr(pattern ='  ',string))+2, nchar(string)))-1}

get_num<- function(string){as.numeric(unlist(gsub("[^0-9]", "", unlist(string)), ""))}

get_x_pixel<- function(string){
  s<-   substr(string, unlist(gregexpr(pattern ='\t',trial_txt[eFix_loc[Fix_b_Bnd]]))[3], 
               unlist(gregexpr(pattern ='\t',trial_txt[eFix_loc[Fix_b_Bnd]]))[4])
  dot<- unlist(gregexpr(pattern ='.', s))
  s<- substr(unlist(gsub("[^0-9]", "", unlist(s)), ""), 1, nchar(unlist(gsub("[^0-9]", "", unlist(s)), ""))-1)
  s<- as.numeric(s)
  return(s)
}
